# Generated by Django 4.1.3 on 2022-11-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='유저 아이디')),
                ('user_password', models.CharField(max_length=30, null=True, verbose_name='유저 비밀번호')),
                ('user_email', models.EmailField(max_length=128, null=True, verbose_name='유저 이메일')),
                ('user_phone', models.CharField(max_length=13, null=True, verbose_name='유저 전화번호')),
                ('user_address', models.CharField(max_length=300, null=True, verbose_name='유저 집주소')),
                ('user_register_dttm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='계정 생성시간')),
            ],
            options={
                'verbose_name': '유저 정보',
                'ordering': ['user_register_dttm'],
            },
        ),
    ]
