# Generated by Django 4.1.3 on 2022-11-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='상품 아이디')),
            ],
            options={
                'verbose_name': '상품 정보',
                'ordering': ['product_id'],
            },
        ),
    ]
