# Generated by Django 4.1.3 on 2022-11-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_imgloc',
            field=models.FileField(blank=True, upload_to='img/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_uploaddate',
            field=models.DateField(auto_now=True),
        ),
    ]
