# Generated by Django 4.1.3 on 2022-11-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_enroll',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='상품 등록일'),
        ),
    ]
